// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddKnowledge(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddKnowledge'](arg1, arg2, arg3, arg4, arg5);
}

export function ApproveProposal(arg1) {
  return window['go']['main']['App']['ApproveProposal'](arg1);
}

export function DeleteKnowledge(arg1) {
  return window['go']['main']['App']['DeleteKnowledge'](arg1);
}

export function EditAndApproveProposal(arg1, arg2) {
  return window['go']['main']['App']['EditAndApproveProposal'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetMemoryStats() {
  return window['go']['main']['App']['GetMemoryStats']();
}

export function GetPendingProposals() {
  return window['go']['main']['App']['GetPendingProposals']();
}

export function GetTimeContext() {
  return window['go']['main']['App']['GetTimeContext']();
}

export function GetWorkspaces() {
  return window['go']['main']['App']['GetWorkspaces']();
}

export function ListKnowledge(arg1) {
  return window['go']['main']['App']['ListKnowledge'](arg1);
}

export function Query(arg1, arg2, arg3) {
  return window['go']['main']['App']['Query'](arg1, arg2, arg3);
}

export function RejectProposal(arg1) {
  return window['go']['main']['App']['RejectProposal'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetWorkspaceToken(arg1, arg2) {
  return window['go']['main']['App']['SetWorkspaceToken'](arg1, arg2);
}

export function StartPolling(arg1) {
  return window['go']['main']['App']['StartPolling'](arg1);
}

export function StopPolling(arg1) {
  return window['go']['main']['App']['StopPolling'](arg1);
}

export function UpdateKnowledge(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateKnowledge'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
