// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {knowledge} from '../models';
import {config} from '../models';
import {mitl} from '../models';
import {main} from '../models';

export function AddKnowledge(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<knowledge.Entry>;

export function ApproveProposal(arg1:string):Promise<void>;

export function DeleteKnowledge(arg1:string):Promise<void>;

export function EditAndApproveProposal(arg1:string,arg2:string):Promise<void>;

export function GetConfig():Promise<config.Config>;

export function GetMemoryStats():Promise<Record<string, number>>;

export function GetPendingProposals():Promise<Array<mitl.Proposal>>;

export function GetTimeContext():Promise<string>;

export function GetWorkspaces():Promise<Array<main.WorkspaceStatus>>;

export function ListAvailableChannels(arg1:string,arg2:boolean):Promise<Array<main.ChannelInfo>>;

export function ListKnowledge(arg1:string):Promise<Array<knowledge.Entry>>;

export function Query(arg1:string,arg2:string,arg3:string):Promise<Array<main.QueryResult>>;

export function RejectProposal(arg1:string):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SetMonitoredChannels(arg1:string,arg2:Array<string>):Promise<void>;

export function SetWorkspaceToken(arg1:string,arg2:string):Promise<void>;

export function StartPolling(arg1:string):Promise<void>;

export function StopPolling(arg1:string):Promise<void>;

export function UpdateKnowledge(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:Array<string>):Promise<void>;

export function Version():Promise<string>;
